<a href="https://colab.research.google.com/github/kritsana3376/DL/blob/main/Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## <font color='red'> Input Name, ID, Section in cell below:</font>

Name: Kritsana Netpugdee

ID: 6210551637

Section: 250

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
# Type your code here:
import numpy as np

#### Create an array of 10 zeros 

In [ ]:
# Type your code here:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# This shows the expected result (Do not run this cell!!!)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
# Type your code here:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# This shows the expected result (Do not run this cell!!!)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [ ]:
# Type your code here:
np.full((10), 5,float)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# This shows the expected result (Do not run this cell!!!)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [ ]:
# Type your code here:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# This shows the expected result (Do not run this cell!!!)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [ ]:
# Type your code here:
np.arange(10, 51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# This shows the expected result (Do not run this cell!!!)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
# Type your code here:
X = np.arange(9)
X.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# This shows the expected result (Do not run this cell!!!)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
# Type your code here:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# This shows the expected result (Do not run this cell!!!)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
# Type your code here:
np.random.random(1,)

array([0.26434928])

In [ ]:
# This shows the expected result (Do not run this cell!!!)
# Don't worry your random number may differ below.

array([0.60295939])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
# Type your code here:
np.random.randn(25,)

array([ 0.63747169,  1.44732229,  0.13674236, -0.31944155, -0.47165445,
       -0.92215451,  0.64065818,  0.36269704,  0.14511291,  1.45018616,
       -0.68998347, -0.03562997,  1.53327881,  0.36694155, -0.76348876,
        1.16456735, -1.90076823, -1.01164284,  1.09364649, -0.18983478,
        0.30428409,  0.31705223, -1.10329436, -0.08334154, -0.70994737])

In [ ]:
# This shows the expected result (Do not run this cell!!!)
# Don't worry your random number may differ below.

array([-0.46539104, -0.64918134, -0.5513326 ,  0.20125558,  0.49466912,
       -0.69084562,  0.08768725,  0.1387637 ,  0.41726016, -1.33492891,
        2.22459213, -0.48049567, -1.44065127, -0.9129756 ,  1.4553028 ,
        1.15989909,  0.29203582,  0.90099295, -0.30631965,  0.39004334,
       -0.51196681, -0.76306014,  0.01426574, -1.49833612,  0.2066832 ])

#### Create the matrix shown below:

In [ ]:
# Do not run this cell!!!

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# Type your code here:
np.arange(0.01, 1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
# Type your code here:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
# This shows the expected result (Do not run this cell!!!)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# A) This shows the expected result (Do not run this cell!!!)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Type your code here to get above expected result A):
mat[2:, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# B) This shows the expected result (Do not run this cell!!!)

20

In [ ]:
# Type your code here to get above expected result B):
mat[3][4]

20

In [ ]:
# C) This shows the expected result (Do not run this cell!!!)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# Type your code here to get above expected result C):
mat[:3, 1:2] 

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# D) This shows the expected result (Do not run this cell!!!)

array([21, 22, 23, 24, 25])

In [ ]:
# Type your code here to get above expected result D):
mat[4:,]

array([[21, 22, 23, 24, 25]])

In [ ]:
# E) This shows the expected result (Do not run this cell!!!)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Type your code here to get above expected result E):
mat[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the values in mat

In [ ]:
# Type your code here:
np.sum(mat)

325

In [ ]:
# This shows the expected result (Do not run this cell!!!)

325

#### Get the standard deviation of the values in mat

In [ ]:
# Type your code here:
np.std(mat)

7.211102550927978

In [ ]:
# This shows the expected result (Do not run this cell!!!)

7.211102550927978

#### Get the sum of all the columns in mat

In [ ]:
# Type your code here:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [ ]:
# This shows the expected result (Do not run this cell!!!)

array([55, 60, 65, 70, 75])

# Great Job!